---

#
# Uninstall rancher-monitoring before installation (default: false)

# rancher_monitoring_clean_install: true

#
# Alertmanager Parameters

# alertmanager_configSecret_name: alertmanager-config-secret-custom

# alertmanager_config: |
#   global:
#     resolve_timeout: 5m
#     opsgenie_api_url: https://api.opsgenie.com/
#   receivers:
#     - name: 'demo-team'
#       opsgenie_configs:
#       - api_key: ""
#         responders:
#         - id: ""
#           name: "demo-team"
#           type: "team"
#         priority: "P2"
#   route:
#     group_by:
#       - job
#     group_interval: 5m
#     group_wait: 30s
#     receiver: 'demo-team'
#     repeat_interval: 12h
#     routes:
#       - match:
#           severity: critical
#         receiver: 'demo-team'

# prometheus_retention: 22d
# prometheus_storage_size: 350Mi

# grafana_storage_enabled: false
