---

- name: Install Cert Manager CRDs
  shell: kubectl apply \
    -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml \
    --kubeconfig {{ kubeconfigPath }}

- name: Add HELM Repo
  shell: |
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

- name: Install Cert Manager
  shell: |
    helm install cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --create-namespace \
      --version {{ cert_manager_version }} \
      --kubeconfig {{ kubeconfigPath }}
